### ISSUE TITLE
How to leverage Tape as disk based BlockingQueue ?

### ISSUE THREAD

**Issue by javajack** [square/tape#121]
I would like to leverage Tape as a BlockingQueue for Executor. ( for Java not Android )

https://docs.oracle.com/javase/7/docs/api/java/util/concurrent/ThreadPoolExecutor.html#ThreadPoolExecutor(int,%20int,%20long,%20java.util.concurrent.TimeUnit,%20java.util.concurrent.BlockingQueue)

Can we leverage Tape for this ? As I can see Tape has a proprietary API. As you have begun Tape2 could this be explored to match  BlockingQueue API with Tape ?

I could see someone has already implemented disk based BlockingQueue.
But it's implementation is messy and maintained, unlike Tape.

https://github.com/Vijay2win/FilebackedBlockingQueue

**Comment by f2prateek** [comment]
To simplify the internals, Tape does not handle concurrency. I don't think there's any reason to add this in Tape itself. It's likely it could be implemented on top of QueueFile (as in done in the library you shared).

**Comment by javajack** [comment]
@f2prateek thanks to clarify.
Do you see any issue in the approach used by library that I shared ?
