### ISSUE TITLE
tape-sample 404 on github

### ISSUE THREAD

**Issue by huiguang-liang** [square/tape#129]
Hi, I'm looking for in-depth sample codes on this library and I keep seeing links to [https://github.com/square/tape/tree/master/tape-sample](url), but going to that address sends me to a github 404 (page not found).

What's happening?

**Comment by f2prateek** [comment]
There are no samples on master currently. You can check out the tag for an older release to see the older samples.

**Comment by preetb123** [comment]
https://github.com/wires/android-standalone-tape-sample
