### ISSUE TITLE
Update maven?

### ISSUE THREAD

**Issue by paulo-raca** [square/tape#133]
The package on maven is 2 years old (v1.2.3).
There has been o lot of development since, can we have a new version on Maven?
(Or is the current version considered unstable?)

**Comment by JakeWharton** [comment]
It's not ready yet. We will release when it's ready. For now snapshots are automatically published. Details on it are in the README.

**Comment by JakeWharton** [comment]
It is much closer than it has been in the last two years though!

**Comment by paulo-raca** [comment]
Thanks
