### ISSUE TITLE
File is corrupt; length stored in header is 0, how to detect issue?

### ISSUE THREAD

**Issue by danvinokour** [square/tape#135]
very small percentage of our users, sometimes get the error:

> Caused by java.io.IOException: File is corrupt; length stored in header is 0.
>        at com.squareup.tape.QueueFile.readHeader(QueueFile.java:165)
>        at com.squareup.tape.QueueFile.(QueueFile.java:117)
>        at com.squareup.tape.FileObjectQueue.(FileObjectQueue.java:35)

we are creating the taskqueue with the following command:
`File taskQueueFile = new File(mContext.getFilesDir(), "taskqueue.db");`

We have hard time to understand why this issue may happen.
Please consider adding more informative message

**Comment by JakeWharton** [comment]
There's no additional information to convey here. The very first bytes we read are the length and if the length is defined as 0 then there's nothing else we can parse. Your best bet is to take the file and upload it as part of the crash report so that you can diagnose the problem.

**Comment by danvinokour** [comment]
We uploaded the file, it has a size of 4k and it has only zero's there.
a valid file has 1000 in the second column, first row.

we have also more info about the path and the permissions is has and everything seems legit. 
what can we do to analyze it further?
