### ISSUE TITLE
 EOFException is not processed while using new file to construct QueueFile.

### ISSUE THREAD

**Issue by Pan-Gao** [square/tape#153]
03-08 18:16:53.163 30491-30491/com.xxx.eventcollectorapp W/System.err: java.io.EOFException
03-08 18:16:53.164 30491-30491/com.xxx.eventcollectorapp W/System.err:     at java.io.RandomAccessFile.readFully(RandomAccessFile.java:418)
03-08 18:16:53.164 30491-30491/com.xxx.eventcollectorapp W/System.err:     at java.io.RandomAccessFile.readFully(RandomAccessFile.java:384)
03-08 18:16:53.164 30491-30491/com.xxx.eventcollectorapp W/System.err:     at com.squareup.tape.QueueFile.readHeader(QueueFile.java:160)
03-08 18:16:53.164 30491-30491/com.xxx.eventcollectorapp W/System.err:     at com.squareup.tape.QueueFile.<init>(QueueFile.java:117)

EOFException is not processed while using new file to construct QueueFile.

and my environment:

    compileSdkVersion 25
    buildToolsVersion "25.0.2"
    defaultConfig {
        minSdkVersion 15
        targetSdkVersion 25
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
    }

    compile 'com.squareup:tape:1.2.3'

**Comment by qiyuanchen** [comment]
Hey I'm having the same issue?
How did you solve it at the end?
