### ISSUE TITLE
[Windows 10 only] Failed to resolve: com.squareup:tape:2.0.0-SNAPSHOT 

### ISSUE THREAD

**Issue by sika78** [square/tape#163]
Today I've started to get this error in Windows (Mac works fine)
![android studio 2 3 2](https://cloud.githubusercontent.com/assets/3920798/26513636/968d8898-423a-11e7-9386-6e54f32a0ca0.png)

I did a search to see if others have this issue but it seems that I'm the only one having this issue out there.
I've clean the project, restart PC, invalidate cache, restart Android Studio, nothing worked!

Any thoughts?
Thanks!

**Comment by f2prateek** [comment]
You typically need to add the snapshot repo to use snapshot builds. Something like https://github.com/segmentio/analytics-java#snapshots

**Comment by sika78** [comment]
I actually did this: 
    maven {
            url 'https://oss.sonatype.org/content/repositories/snapshots'
        }

I've double check it and it still fails.

**Comment by sika78** [comment]
``

**Comment by NightlyNexus** [comment]
From your screenshot, it looks like your specified group id might be out of date.
`compile 'com.squareup.tape2:tape:2.0.0-SNAPSHOT'` is what you want under your dependencies.

**Comment by f2prateek** [comment]
^ that sounds right to me.
