### ISSUE TITLE
Drop Serializable from Task

### ISSUE THREAD

**Issue by pforhan** [square/tape#17]
We shouldn't mandate serializable.  Note: For downstream classes, this is probably a non-compatible change; if they were depending on Serialization then they will need to implement serializable themselves.

You *can* deserialize non-serializable classes, but I need to do a refresher on whether this changes semantics of the process.

**Comment by JakeWharton** [comment]
Task is gone.

**Comment by JakeWharton** [comment]
And so is SerializableConverter!

**Comment by f2prateek** [comment]
Haha you just beat me to this!
