### ISSUE TITLE
When do you think you will finish the verson 2.0 ? 

### ISSUE THREAD

**Issue by eotin** [square/tape#171]

**Comment by JakeWharton** [comment]
We don't know. You can use the SNAPSHOT for now.

**Comment by eotin** [comment]
Thanks !
Problem is that I don’t find the snapshot jar file


Best regards,
Novel-T Sàrl
Emmanuel OTIN - Solutions Engineer
W: www.novel-t.ch<http://www.novel-t.ch/> | @: eo@novel-t.ch<mailto:eo@novel-t.ch>

**Comment by JakeWharton** [comment]
The repository containing the artifact is https://oss.sonatype.org/content/repositories/snapshots/

**Comment by eotin** [comment]
Thanks a lot but I’m lost.
I don’t know where to find it.

Thanks for your help.


Best regards,
Novel-T Sàrl
Emmanuel OTIN - Solutions Engineer
W: www.novel-t.ch<http://www.novel-t.ch/> | @: eo@novel-t.ch<mailto:eo@novel-t.ch>

**Comment by NightlyNexus** [comment]
Are you using Gradle?
You'll have something like:
```
repositories {
  mavenCentral()
  maven { url 'https://oss.sonatype.org/content/repositories/snapshots/' }
}
```
and 
```
dependencies {
  implementation 'com.squareup.tape2:tape:2.0.0-SNAPSHOT'
}
```

**Comment by NightlyNexus** [comment]
Also, direct link: https://oss.sonatype.org/content/repositories/snapshots/com/squareup/tape2/tape/2.0.0-SNAPSHOT/

**Comment by eotin** [comment]
Thank you very much.
Yes I’m using gradle.


Best regards,
Novel-T Sàrl
Emmanuel OTIN - Solutions Engineer
W: www.novel-t.ch<http://www.novel-t.ch/> | @: eo@novel-t.ch<mailto:eo@novel-t.ch>
