### ISSUE TITLE
Cannot resolve createInMemory()

### ISSUE THREAD

**Issue by ghanendrapiplani** [square/tape#172]
I am following the docs on github and getting error         
`ObjectQueue<String> queue = ObjectQueue.createInMemory(); 
Cannot resolve method createInMemory.`
I have included the jar file 1.2.3 into android project.

**Comment by JakeWharton** [comment]
The README is for the code on `master`, not the latest release. Unfortunately GitHub doesn't let us differentiate.

The version for the stable release actually doesn't have any info: https://github.com/square/tape/tree/tape-parent-1.2.3#readme. Have you looked at the website? http://square.github.io/tape/
