### ISSUE TITLE
Multiple thread processing the queue

### ISSUE THREAD

**Issue by dhruv-bansal** [square/tape#175]
Do queue support multi-thread processing? What will happen if multiple threads write in the queue? What if multiple threads process from the queue?
Writes:
I could see the documentation, writes are synchronous - Does it makes this queue not suitable for writing in highly concurrent scenarios? 
I could see we have two methods seek() and then remove(). This makes processing of queue elements by multiple threads tricky. 
Why can't we have a method which read and remove the element from the top of the queue atomically? In that way, the queue could be processed by multiple threads.

**Comment by bangarharshit** [comment]
From JavaDoc of the queue file - https://github.com/square/tape/blob/master/tape/src/main/java/com/squareup/tape2/QueueFile.java#L38 - It is not synchronized and it is up to the caller.

**Comment by f2prateek** [comment]
Yes, the current implementation is not suitable for concurrent use.
