### ISSUE TITLE
Can't get tape dependency through the following xml section.

### ISSUE THREAD

**Issue by kenshinji** [square/tape#176]
````
<dependency>
  <groupId>com.squareup.tape2</groupId>
  <artifactId>tape</artifactId>
  <version>2.0.0-SNAPSHOT</version>
</dependency>
````
The above one described in **README.md** can't be resolved through Maven. 

However the following works.

````
<dependency>
    <groupId>com.squareup</groupId>
    <artifactId>tape</artifactId>
    <version>1.2.3</version>
</dependency>
````

**Comment by f2prateek** [comment]
You also need the snapshot repo, something like this https://github.com/segmentio/analytics-java/blob/master/README.md#snapshots

**Comment by kenshinji** [comment]
@f2prateek yeah, it works. thank you very much.
