### ISSUE TITLE
Unable to get maven dependency

### ISSUE THREAD

**Issue by choiyoung206** [square/tape#182]
I created a project and added maven dependency of tape, but I'm unable to build my project and getting following error
`org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal on project TestQueue: Could not resolve dependencies for project com.test:TestQueue:jar:0.0.1-SNAPSHOT: Could not find artifact com.squareup.tape2:tape:jar:2.0.0-SNAPSHOT`

I have added following dependency in my pom

`<dependency>`
`	<groupId>com.squareup.tape2</groupId>`
`	<artifactId>tape</artifactId>`
`	<version>2.0.0-SNAPSHOT</version>`
`</dependency>`

**Comment by f2prateek** [comment]
You need to add the snapshots repo, something like this https://github.com/segmentio/analytics-java/blob/master/README.md#snapshots
