### ISSUE TITLE
Is it thread safe?

### ISSUE THREAD

**Issue by choiyoung206** [square/tape#183]
I was looking into the description of tape but couldn't find if this queue is thread safe or not. I want to use the queue in a multi-threaded environment where concurrent reads and writes will happen.
So I'm confused if I can use this queue in such situations or not.

**Comment by JakeWharton** [comment]
No. None of the types are safe for concurrent use. You either need to synchronize on the instance or use some sort of single-threaded message passing system like an actor, executor, etc. to move all interaction to a single thread.

**Comment by amalic** [comment]
I believe thread safety out of the box would be a nice feature for java micro services.

**Comment by JakeWharton** [comment]
I don't see how those are correlated. Java's collections and I/O primitives aren't thread safe either and require external synchronization or wrappers.
