### ISSUE TITLE
Android module for android specific logic

### ISSUE THREAD

**Issue by bangarharshit** [square/tape#184]
One of the most common use cases for tape is to design network requests on android. Android has several constraints such as `battery` or `network` and can be abstracted out in a very small module (these things can be useful for non-network tasks also).

Do you think if it makes sense to have a very small android specific module (pluggable to add implementor specific logic) to support some of these constraints?

**Comment by JakeWharton** [comment]
That sounds like a task for JobScheduler which interacts with the queue for
the work it needs to perform.

**Comment by bangarharshit** [comment]
Sounds good.
