### ISSUE TITLE
Not compatible with Gradle 5.1.1

### ISSUE THREAD

**Issue by ber4444** [square/tape#205]
Cannot access class 'com.squareup.tape2.ObjectQueue.Converter'. Check your module classpath for missing or conflicting dependencies

**Comment by ber4444** [comment]
Actually, it's more of an issue with gradle-5.1.1-all which in turn is required with the new R8-by-default Android plugin (3.4.0).

**Comment by JakeWharton** [comment]
We ship that class. What makes you think that Tape is the problem? Can you reproduce in a sample?

**Comment by string-areeb** [comment]
Are you using tape as a transitive dependency of some other library? If so, add it as an explicit dependency

**Comment by ber4444** [comment]
I added the stacktrace to this report: https://issuetracker.google.com/issues/130746805
We use tape in an inhouse library which we include with "implementation" in gradle ("changing = true" is added if that matters), and the lib itself is using "implementation" to include "2.0.0-beta1" of tape.

**Comment by ber4444** [comment]
So I think @string-areeb 's solution works. Thanks!

**Comment by JakeWharton** [comment]
This doesn't appear to be a Tape issue but rather a build system one.
