### ISSUE TITLE
QueueFile#forEach(ElementVisitor reader) should return number of elements read

### ISSUE THREAD

**Issue by f2prateek** [square/tape#69]
Currently `QueueFile#forEach(ElementVisitor reader)` returns void, which means callers have to keep track of how many elements were read.

```java
int read = queueFile.forEach(visitor);
queueFile.remove(read);
```

**Comment by JakeWharton** [comment]
Let me ship `master` then lets make some breaking API changes.

**Comment by JakeWharton** [comment]
(such as this one)

**Comment by JakeWharton** [comment]
Actually we haven't shipped this interface yet!
