### ISSUE TITLE
tape:1.3.0 not released

### ISSUE THREAD

**Issue by ersin-ertan** [square/tape#73]
Change log is update for version 1.3.0 and is set as 2015-01-06

Releases only show up to [1.2.3](https://github.com/square/tape/releases)

compile 'com.squareup:tape:1.3.0' is not working

**Comment by JakeWharton** [comment]
Thanks. I changed it back to "In Development". We're still debating one of the new APIs and aren't quite ready to pull the trigger yet.

**Comment by jensck** [comment]
What's the status on this?  Is this new API still being discussed?
