### ISSUE TITLE
Return removed item in onRemove()

### ISSUE THREAD

**Issue by oliverhausler** [square/tape#78]
In ObjectQueue, `onAdd(ObjectQueue<Channel> queue, Channel channel)` returns the added item, but `onRemove(ObjectQueue<Channel> queue)` does not. The same, and contrary to many Java collection classes, `remove()` does not return the removed item either.

I understand this is an optimization for speed, but what's the sense of onRemove() if it doesn't tell me which item has been removed? Normally, I would want to use the listener to sync the queue with the UI, or similar. As you have it now, I need to do that manually for remove, which is not very clean.

You may consider this change for 1.3.0.

**Comment by Ewg777** [comment]
oliverhausler, have found solution for this issue? http://stackoverflow.com/questions/29553756/take-a-photo-while-video-is-being-streamed-using-webrtc-on-android-native/30300761

**Comment by pforhan** [comment]
It's not so much an optimization for speed as for reliability.  The intent was to be absolutely certain that an entry has been processed *before* removing it from the queue, so the API was written that way: you have to read to get the entry as a separate step before doing a remove.

A related concept then is that actions stored in tape queues should be idempotent.  A client may well end up processing a given entry multiple times before it's removed.

I'm not saying we'd design the API again this way were we starting over, but that's at least the gist of why it is the way it is.

**Comment by oliverhausler** [comment]
Understand, and as it is file-based, this definitely makes sense. You can close this issue if you like.
