### ISSUE TITLE
Clarification on concurrency

### ISSUE THREAD

**Issue by mpj** [square/tape#86]
I've been programming for many years, but I'm relatively new to Java and Android development, so please excuse if this is a noobish question asked in the wrong place. Any help is greatly appreciated.

Can somebody please explain to me how to deal with concurrency with tape? I'm building an android client that writes logs to the tape queue as stuff happens, and a few times every day, PeriodicTask kicks off logic that empties the queue and writes it to a remote server. If both of these processes execute at the same time (the appending and the peeking) will that be handled by tape, or will it corrupt the file? If the latter, is there a common or best practice approach to deal with this problem?

**Comment by pforhan** [comment]
Tape does no concurrency for you.  The javadoc for a couple of classes (like [FileObjectQueue](https://github.com/square/tape/blob/6bed87308bf7706eb7a2bc7b40e19096aada6e0f/tape/src/main/java/com/squareup/tape/FileObjectQueue.java)) states that you should perform all operations for a given queue on the same thread.  This thread doesn't have to be the main thread, but you should always use the same one for consistency.

**Comment by mpj** [comment]
@pforhan Thank you. That helps me a lot. 

I saw that in the comment, but the way it was worded made it unclear if it was just the class that needed to be kept in the same thread or all file access.
